# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e81867a80b484a8d4860b739d297cfabf3bb3fae57f408f474c12a243e109a21a7bd78dd1897dffb788f8f30302821eb097827c6843ba157c0b105e90f987b06

test:
  secret_key_base: 75844198ee1a44fe434de97068cc1d3c7ed373bd372e1b4b1a2d9c54a4393c909b8b8fb2d57126cab3cb2da3fe5c55e67b71e13d223d9942c4753a23e516b990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
